name: Run unit tests on every push

on: [push]

jobs:
  build:
    name: Build wheels for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          PIPX_BIN_DIR=/usr/local/bin pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Set Poetry environment
        run: |
          poetry env use ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Build wheels
        run: |
          poetry build

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.whl

      - name: Upload source distribution
        uses: actions/upload-artifact@v2
        if: matrix.python-version == '3.8'
        with:
          path: dist/*.tar.gz
