name: Build wheels

on: 
  push:
    paths:
      # only build wheels when the package code changes
      - 'woc/**'
      - 'setup.py'

jobs:
  build-wheel:
    name: wheels
    runs-on: ubuntu-latest
    # only on default branch
    if: github.ref_name == github.event.repository.default_branch

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env:
          CIBW_BUILD: cp3{8,9,10,11}-manylinux_x86_64
          # force manylinux2014 to avoid compatibility issues on RHEL 7
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          # install required dependencies： bz2
          CIBW_BEFORE_ALL: yum install -y bzip2-devel

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.whl

  build-sdist:
    name: sdist
    runs-on: ubuntu-latest
    # only on default branch
    if: github.ref_name == github.event.repository.default_branch

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build source distribution
        run: pipx run build --sdist

      - name: Upload source distribution
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/*.tar.gz
